const projects = [
  // title, cateory, client,year, description,tags, link,images
  {
    projectTitle: "BODYARMOR",
    category: "Development",
    client: "A Unified Whole",
    year: "2025",
    description: "",
    tags: ["Shopify/Hydrogen", "React.js", "GSAP"],
    link: "https://www.drinkbodyarmor.com/",
    videoSrc: "/bodyarmor.mp4",
  },
  {
    projectTitle: "From The Farm",
    category: "Development",
    client: "A Unified Whole",
    year: "2025",
    description: "",
    tags: ["Shopify/Hydrogen", "React.js", "GSAP"],
    link: "https://www.fromthefarmco.com",
    videoSrc: "/fromthefarm.mp4",
  },
  {
    projectTitle: "Hotel Kühbacher",
    category: "Development",
    client: "A Unified Whole",
    year: "2025",
    description: "",
    tags: ["Shopify/Hydrogen", "React.js", "GSAP"],
    link: "https://hotel-kuehbacher.com/",
    videoSrc: "/hotel-kuehbacher.mp4",
  },
  {
    projectTitle: "Lou Phelps",
    category: "Development",
    client: "A Unified Whole",
    year: "2025",
    description: "",
    tags: ["Shopify/Hydrogen", "React.js", "GSAP"],
    link: "https://louphelps.com/",
    videoSrc: "/lou-phelps.mp4",
  },
  // {
  //   projectTitle: "A Unified Whole",
  //   category: "Web Development",
  //   client: "A Unified Whole",
  //   year: "2025",
  //   description:
  //     "Developed a custom Shopify website for From The Farm that brings their brand to life online. Inspired by their vintage aesthetic and rooted identity, the site combines clean design with nostalgic touches, making it easy for customers to explore and shop their full range of products.",
  //   tags: ["Next.js", "Tailwind CSS", "GSAP"],
  //   link: "https://auw.webflow.io/",
  //   videoSrc: "https://www.aunifiedwhole.com/aunifiedwhole.mp4",
  // },
  {
    projectTitle: "Prudentos",
    category: "Design, Development",
    client: "Samira Prudentos",
    year: "2024",
    description:
      "A comprehensive e-commerce store designed for Samira Prudentos, showcasing handmade garments crafted in Berlin.",
    tags: ["Next.js", "Tailwind CSS", "Framer Motion", "Shopify"],
    link: "https://www.samira-prudentos.com",
    videoSrc: "/samira.mp4",
  },
  {
    projectTitle: "Photography Portfolio",
    client: "Meklit Fekadu",
    category: "Design, Development",
    year: "2024",
    description:
      "A photography portfolio designed for Meklit Fekadu, a Berlin-based photographer.",
    tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
    link: "https://www.meklitfekadu.com",
    videoSrc: "/meki.mp4",
  },
  {
    projectTitle: "Secret Nature",
    category: "Development",
    client: "A Unified Whole",
    year: "2025",
    description:
      "Developed a custom Shopify website for From The Farm that brings their brand to life online. Inspired by their vintage aesthetic and rooted identity, the site combines clean design with nostalgic touches, making it easy for customers to explore and shop their full range of products.",
    tags: ["Shopify/Hydrogen", "React.js", "GSAP"],
    link: "https://www.secretnature.co/",
    videoSrc: "/meki.mp4",
  },
  // {
  //   projectTitle: "Design Portfolio",
  //   category: "Development",
  //   client: "Matteo Just",
  //   year: "2024",
  //   description:
  //     "A portfolio website developed for Matteo Just, a Munich-based transportation designer. (Work in Progress)",
  //   tags: ["Next.js", "Tailwind CSS", "Framer Motion", "GSAP"],
  //   link: "https://matteo-just-xtdn.vercel.app/",
  //   images: [
  //     "matteo/matteo_1.webp",
  //     "matteo/matteo_2.webp",
  //     "matteo/matteo_3.webp",
  //   ],
  // },
  // {
  //   projectTitle: "Producer Portfolio",
  //   category: "Web Design, Development",
  //   client: "Alba Preysing",
  //   year: "2023",
  //   description:
  //     "A modern and visually engaging portfolio created for a Freelance Producer and founder of Tête-à-tête dining.",
  //   tags: ["Next.js", "Tailwind CSS", "GSAP"],
  //   link: "https://www.albapreysing.com/",
  //   images: ["alba/alba1.webp", "alba/alba2.webp", "alba/alba3.webp"],
  // },
  // {
  //   projectTitle: "Model Agency",
  //   category: "Web Design, Development",
  //   client: "The Agents - Amsterdam",
  //   year: "2024",
  //   description:
  //     "Designed and developed the website for The Agents, a model management agency in Amsterdam.",
  //   tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
  //   link: "https://www.theagentsmodelmanagement.com",
  //   images: [
  //     "esme/theagents1.webp",
  //     "esme/theagents3.webp",
  //     "esme/theagents2.webp",
  //   ],
  // },
];

export default projects;
