import localFont from "next/font/local";
import "./globals.css";
import StickyFooter from "../components/StickyFooter";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Malik Kotb - Front End Developer",
  description: "Generated by Malik Kotb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
        <StickyFooter />
      </body>
    </html>
  );
}
